name: Test Site 001
favicon: null
layout_spectrum: 0.3714760821312666
typography_spectrum: 0.10717168706469238
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.283502290956676
  lightness: 0.29824425117112696
  saturation: 0.6912476366851479
  rhythmicContrast: 0.08248923672363162
purpose: []
